[package]
name = "spotify-visualizer"
version = "0.1.0"
edition = "2021"


[build-dependencies]
tauri-build = { version = "2", features = [] }


[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"


[features]
default = []
